alias g='git'
alias ga='git add'
alias gaa='git add .'
alias gb='git branch'
alias gc='git commit'
alias gco='git checkout'
alias gd='git diff'
alias gm='git merge'
alias gpull='git pull'
alias gpush='git push'
alias gr='git restore'
alias gs='git status'
alias gst='git stash'
alias gsta='git stash apply'
alias gstp='git stash pop'
alias glog="git log --pretty=format:'%C(green)%h%C(reset) - %C(blue)%ad %C(magenta)%an %C(reset)%s%C(yellow)%d' --decorate --date=format:'%Y-%m-%d %H:%M' --abbrev-commit --no-merges"
